before:
  hooks:
    - make setup
    - git checkout -- go.mod
    - git checkout -- go.sum
    - make generate
builds:
- goos:
  - darwin
  - linux
  - windows
  env:
  - CGO_ENABLED=0
  - GO111MODULE=on
archives:
- format_overrides:
    - goos: windows
      format: zip
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
