defaults: &defaults
  docker:
    - image: circleci/golang:1.13
  environment:
    GO111MODULE: "on"

version: 2
jobs:
  test:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - go-module-cache-v1-{{ checksum "~/project/go.sum" }}
            - go-module-cache-v1-
      - run: go mod download
      - save_cache:
          key: go-module-cache-v1-{{ checksum "~/project/go.sum" }}
          paths:
            - ~/go/pkg/mod/cache
      - run: make build
      - run: make test
      - run: make codecov
  release:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - go-module-cache-v1-{{ checksum "~/project/go.sum" }}
            - go-module-cache-v1-
      - run: curl -sL https://git.io/goreleaser | bash

workflows:
  version: 2
  test_and_release:
    jobs:
      - test:
          filters:
            branches:
              only: /.*/
            tags:
              only: /.*/
      - release:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v[0-9]+(\.[0-9]+)*(-.*)*/
          requires:
            - test
