defaults: &defaults
  docker:
    - image: circleci/golang:1.12
  working_directory: /go/src/github.com/mpppk/goofy

version: 2
jobs:
  test:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: vendor-{{ checksum "Gopkg.lock" }}

      # specify any bash command here prefixed with `run: `
      - run: make setup
      - run: make build
      - run: make test
      - run: make codecov
      - save_cache:
          key: vendor-{{ checksum "Gopkg.lock" }}
          paths:
          - vendor
  release:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: vendor-{{ checksum "Gopkg.lock" }}
      - run: curl -sL https://git.io/goreleaser | bash

workflows:
  version: 2
  test_and_release:
    jobs:
      - test:
          filters:
            branches:
              only: /.*/
            tags:
              only: /.*/
      - release:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v[0-9]+(\.[0-9]+)*(-.*)*/
          requires:
            - test
