name: Go
on: [push]
jobs:

  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu16.04
          - ubuntu18.04
        goversion:
          - 1.11
          - 1.12
    steps:

    - name: Set up Go ${{ matrix.goversion }}
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.goversion }}
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

#     - name: Get dependencies
#       run: |
#         go get -v -t -d ./...

    - name: Build
      run: go build -v .
